version: "3.9"

services:
  postgresql:
    container_name: db
    image: postgres:15.3-alpine
    environment:
      POSTGRES_DATABASE: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_ALLOW_EMPTY_PASSWORD: 1

    ports:
      - "5432:5432"
    networks:
      - docker-net

    volumes:
      - ./tables/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql

# allows docker services to communicate
networks:
  docker-net:
    driver: bridge
