spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: POSTGRESQL
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        format_sql: false
        generate_statistics: false

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:6000/social_media
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:password}
    driverClassName: org.postgresql.Driver

  liquibase:
    change-log: classpath:/changelog/db.changelog-master.xml
    enabled: true
